@base_url = http://127.0.0.1:6543/api/v1
@tokenAdmin = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJzdWIiOjEsImlhdCI6MTY5ODMzNDY1MSwiZXhwIjoxNjk4MzM4MjUxfQ.KaEFvCeoBMbUZ1Ibb-FKTQM259x9Hg60knUlBW_qjSrsruCiz2UArRqqnQwfWDtEh1VTATThJbKVyQRV-PXOVA
@tokenUser = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInN1YiI6MiwiaWF0IjoxNjk4MzM0Njg4LCJleHAiOjE2OTgzMzgyODh9.ZO1i6UXx-PrFJxrXnXTK1RIbMpdNWS3vBc8zJqfY_-9QdvSXxke1Sd-wzH9fVyjV_BRnl6J93ZaDQfaF8_EhBw

### GET all users
GET {{base_url}}/users
Authorization:Bearer {{tokenAdmin}}

### GET All Article
GET {{base_url}}/articles
Authorization:Bearer {{tokenUser}}

### create articles
POST {{base_url}}/articles
Authorization:Bearer {{tokenAdmin}}

{

    "title": "Article 1",
    "content": "Content 1"
}

### update articles
PUT {{base_url}}/articles
Authorization: Bearer {{tokenUser}}

{
    "id": 1,
    "title": "Testing update",
    "content": "Content 1"
}

### delete articles
DELETE {{base_url}}/articles
Authorization: Bearer {{tokenAdmin}}

{
    "id": 2
}


### POST login
POST {{base_url}}/login

{
    "username": "user2",
    "password": "password"
}

### POST register
POST {{base_url}}/register

{
    "username": "user2",
    "password": "password"
}


### GET logout
GET {{base_url}}/logout
